[package]
authors = ["Ronald Kinard <furyhunter600@gmail.com>", "Andrea Ciliberti <meziu210@icloud.com>"]
description = "A safe wrapper around smealum's ctrulib."
license = "MIT/Apache 2.0"
name = "ctru-rs"
version = "0.7.1"
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]
name = "ctru"

[dependencies]
libc = { git = "https://github.com/Meziu/libc.git" }
linker-fix-3ds = { git = "https://github.com/Meziu/rust-linker-fix-3ds.git" }
bitflags = "1.0.0"
widestring = "0.2.2"
